<?php

namespace CelciusTech\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Get Query for find all posts
     *
     * @return Query
     */
    public function findAllQuery()
    {
        $em = $this->getEntityManager();

        return $em->createQuery('
          SELECT p FROM CelciusTechBlogBundle:Post p
          ORDER BY p.created DESC
        ');
    }
}
